# Generated by Django 4.2.1 on 2023-05-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("Бакалавриат", "Бакалавриат"),
                    ("Магистратура", "Магистратура"),
                    ("Аспирантура", "Аспирантура"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[
                    ("Первый", "Первый"),
                    ("Второй", "Второй"),
                    ("Третий", "Третий"),
                    ("Четвертый", "Четвертый"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                default=0,
            ),
        ),
    ]
