# Generated by Django 4.2.1 on 2023-05-31 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_course_level_alter_course_semester_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="credit",
        ),
    ]
