# Generated by Django 4.2.1 on 2023-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_dep_head",
        ),
        migrations.AlterField(
            model_name="parent",
            name="relation_ship",
            field=models.TextField(
                blank=True, choices=[("Папа", "Папа"), ("Мама", "Мама")]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("СПО", "СПО"),
                    ("Бакалавриат", "Бакалавриат"),
                    ("Магистратура", "Магистратура"),
                    ("Аспирантура", "Аспирантура"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
