# Generated by Django 4.2.1 on 2023-05-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_remove_user_is_dep_head_alter_parent_relation_ship_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="patronymic"
            ),
        ),
    ]
